tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      database: TASTY_BYTES_DBT_DB
      schema: DEV
      warehouse: COMPUTE_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      database: TASTY_BYTES_DBT_DB
      schema: PROD
      warehouse: COMPUTE_WH
